CREATE TABLE BLOG_T2 (
BLOG_NO NUMBER NOT NULL PRIMARY KEY,
TITLE   VARCHAR2(255 BYTE) NOT NULL,
EDITOR  VARCHAR2(255 BYTE) NOT NULL,
CONTENTS CLOB,
CREATED DATE NOT NULL
);


INSERT INTO BLOG_T(BLOG_NO, TITLE, EDITOR, CREATED) VALUES(1, '테스트', '에디터', SYSDATE);

DROP TABLE BLOG_T2;

