SELECT SUM(MIN_SALARY) AS MIN_SUM FROM JOBS
GROUP BY MIN_SALARY
ORDER BY MIN_SUM DESC;

SELECT *  -- 실제 개발할때는 * 사용 금지
FROM EMPLOYEES;

SELECT AVG(SALARY) AS SAL_AVG FROM EMPLOYEES
GROUP BY SALARY
ORDER BY SAL_AVG DESC;

SELECT JOB_ID,
  AVG(SALARY) AS SAL_AVG
  FROM EMPLOYEES
GROUP BY JOB_ID
ORDER BY SAL_AVG DESC;

SELECT * FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'A%';

SELECT CONCAT(FIRST_NAME,LAST_NAME)AS FULL_NAME FROM EMPLOYEES;

--2. 부서 테이블의 모든 칼럼을 조회하시오. 조회할 칼럼명을 지정 '부서번호', '부서명', '위치'
select * from DEPARTMENTS;