/* 
    다대다 관계
    1. 2개의 테이블을 직접 관계 짓는 것은 불가능하다.
    2. 다대다 관계를 가지는 2개의 테이블과 연결될 중간 테이블이 필요하다.
    3. 일대다 관계를 2개 만들면 다대다 관계가 된다.

*/

--스스로 한것
-- 학생 테이블
CREATE TABLE STUDENT(
STUDENT_NO NUMBER NOT NULL PRIMARY KEY,
NAME VARCHAR2(255) NOT NULL,
GRADE NUMBER NOT NULL,
CLASS NUMBER NOT NULL,
PHONE_NUMBER NUMBER
);

--선생님 코드
--학생 테이블
CREATE TABLE STUDENT_T(
STUDENT_NO NUMBER NOT NULL PRIMARY KEY,
STUDENT_NAME VARCHAR2(255) NOT NULL,
STUDENT_GRADE NUMBER NOT NULL,
STUDENT_CLASS NUMBER NOT NULL,
STUDENT_NUMBER NUMBER
);

--ALTER TABLE STUDENT MODIFY PHONE_NUMBER VARCHAR2(255) ;
--ALTER TABLE STUDENT DROP CONSTRAINT ENROLL;

-- 스스로 한것
--과목테이블
CREATE  TABLE SUBJECT(
SUBJECT_NO NUMBER  NOT NULL PRIMARY KEY,
NAME VARCHAR2(255) NOT NULL
);

--선생님코드
--과목 테이블
CREATE  TABLE SUBJECT_T(
SUBJECT_NO NUMBER  NOT NULL PRIMARY KEY,
SUBJECT_NAME VARCHAR2(255) NOT NULL
);

--ALTER TABLE SUBJECT
--ADD CONSTRAINT ENROLL FOREIGN KEY (SUBJECT_NO) REFERENCES SUBJECT(SUBJECT_NO);

--스스로 한것
--수강신청 테이블
CREATE TABLE ENROLL(
STUDENT_NO NUMBER NOT NULL,
SUBJECT_NO NUMBER NOT NULL,
CONSTRAINT ENROLL_STUDENT_FK FOREIGN KEY (STUDENT_NO) REFERENCES STUDENT(STUDENT_NO),
CONSTRAINT ENROLL_SUBJECT_FK FOREIGN KEY (SUBJECT_NO) REFERENCES SUBJECT(SUBJECT_NO)
);

--선생님 코드
--수강신청 테이블
CREATE TABLE ENROLL_T(
ENROLL_NO NUMBER NOT NULL PRIMARY KEY,
STUDENT_NO NUMBER NOT NULL,
SUBJECT_NO NUMBER NOT NULL,
CONSTRAINT ENROLL_STUDENT_FK FOREIGN KEY (STUDENT_NO) REFERENCES STUDENT_T(STUDENT_NO) ON DELETE CASCADE,
CONSTRAINT ENROLL_SUBJECT_FK FOREIGN KEY (SUBJECT_NO) REFERENCES SUBJECT_T(SUBJECT_NO) ON DELETE SET NULL
);

DROP TABLE ENROLL_T;
DROP TABLE STUDENT_T;
DROP TABLE SUBJECT_T;

--CREATE TABLE ENROLL(
--STUDENT_NO NUMBER NOT NULL
--CONSTRAINT STUDENT_NO FOREIGN KEY(STUDENT_NO) REFERENCES STUDENT (STUDENT_NO),
--SUBJECT_NO NUMBER NOT NULL
--CONSTRAINT SUBJECT_NO FOREIGN KEY(SUBJECT_NO) REFERENCES SUBJECT (SUBJECT_NO)
--);

--INSERT INTO STUDENT VALUES(10101, '김은지', 3, 5, '010-1234-1234 ');
--INSERT INTO SUBJECT VALUES (12345, 'JAVA');
--
--SELECT * FROM STUDENT;
--SELECT * FROM SUBJECT;
